services:
    vkr_translation.algorithms.default:
        class: VKR\TranslationBundle\Services\Algorithms\DefaultAlgorithm
        arguments:
            - "@vkr_translation.drivers.doctrine"
            - "@vkr_translation.drivers.google"
            - "@vkr_translation.drivers.entity"

    vkr_translation.algorithms.no_translation:
        class: VKR\TranslationBundle\Services\Algorithms\NoTranslationAlgorithm
        arguments:
            - "@vkr_translation.drivers.doctrine"

    vkr_translation.algorithms.on_demand:
        class: VKR\TranslationBundle\Services\Algorithms\OnDemandAlgorithm
        arguments:
            - "@vkr_translation.drivers.doctrine"
            - "@vkr_translation.drivers.google"

    vkr_translation.translation_manager:
        class: VKR\TranslationBundle\Services\TranslationManager
        arguments:
            - "@=service(parameter('vkr_translation.locale_retriever_service'))"
            - "@vkr_translation.translated_field_setter"
            - "@vkr_translation.algorithms.default"

    vkr_translation.translation_updater:
        class: VKR\TranslationBundle\Services\TranslationUpdater
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@vkr_translation.class_checker"
            - "%vkr_translation.language_entity%"

    vkr_translation.translated_field_setter:
        class: VKR\TranslationBundle\Services\TranslatedFieldSetter

    vkr_translation.class_checker:
        class: VKR\TranslationBundle\Services\TranslationClassChecker

    vkr_translation.drivers.doctrine:
        class: VKR\TranslationBundle\Services\DoctrineTranslationDriver
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%vkr_translation.language_entity%"

    vkr_translation.drivers.entity:
        class: VKR\TranslationBundle\Services\EntityTranslationDriver
        arguments:
            - "@vkr_translation.class_checker"

    vkr_translation.drivers.google:
        class: VKR\TranslationBundle\Services\GoogleTranslationDriver
        arguments:
            - "@vkr_translation.class_checker"
            - "@vkr_translation.decorators.google_client"
            - "@=container.hasParameter('vkr_translation.google_api_key') ? parameter('vkr_translation.google_api_key') : ''"

    vkr_translation.decorators.google_client:
        class: VKR\TranslationBundle\Decorators\GoogleClientDecorator

    vkr_translation.translation_proxy_factory:
        class: VKR\TranslationBundle\Services\TranslationProxyFactory
        arguments:
            - "@vkr_translation.class_checker"
            - "@vkr_translation.translation_manager"
        lazy: true

    vkr_translation.doctrine_event_subscriber:
        class: VKR\TranslationBundle\Services\TranslationEventSubscriber
        calls:
            - [ "setTranslationProxyFactory", ["@vkr_translation.translation_proxy_factory"]]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
